# Generated by Django 6.0.4 on 2026-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolset', '0002_rename_output_text_toolactivity_result_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolactivity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolactivity',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolactivity',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='completed', max_length=16),
        ),
        migrations.AlterField(
            model_name='tool',
            name='task_type',
            field=models.CharField(choices=[('word_count', 'Word Counter'), ('reverse_text', 'Text Reverser'), ('youtube_download', 'YouTube Downloader (yt-dlp)'), ('instagram_download', 'Instagram Downloader (yt-dlp)'), ('facebook_download', 'Facebook Downloader (yt-dlp)'), ('tiktok_download', 'TikTok Downloader (yt-dlp)'), ('soundcloud_download', 'SoundCloud Downloader (yt-dlp)'), ('twitter_download', 'Twitter/X Downloader (yt-dlp)'), ('msg_reader', '.msg Reader'), ('image_editor', 'Image Editor')], max_length=32),
        ),
    ]
